Add validators.
Signed-off-by: Eric Myhre <hash@exultant.us>

diff --git a/goad b/goad
--- a/goad
+++ b/goad
@@ -90,11 +90,36 @@ else
 		done
 		rm -f "$coverFile"
 		;;
+	validate)
+		# run all validations and exit non-zero after all of them if any fail
+		validators=()
+		validators+=("./contrib/validate-dco")
+		validators+=("./contrib/validate-gofmt")
+		invalid=""
+		for validator in ${validators[@]}; do
+			echo -e "\E[1;34m==== checking $validator ... ====\E[0;m"
+			"$validator" && {
+				echo -e "\E[1;32mpassed.\E[0;m"
+			} || {
+				echo -e "\E[1;31mfailed!\E[0;m"
+				invalid="true"
+			}
+			echo
+			echo
+		done
+		echo
+		[ -z "$invalid" ] && {
+			echo -e "\E[1;32mall validations green.\E[0;m"
+		} || {
+			echo -e "\E[1;41msome validations failed!\E[0;m"
+			exit 6
+		}
+		;;
 	clean)
 		rm -rf "$GOPATH/bin" "$GOPATH/pkg" "$GOPATH/tmp"
 		;;
 	*)
-		echo "Usage: $0 {init|test|install|fmt|doc|cover|clean}" 1>&2;
+		echo "Usage: $0 {init|test|install|fmt|doc|cover|validate|clean}" 1>&2;
 		exit 1
 	;;
 esac
